import type { Metadata } from 'next';
import { Clock, Instagram, MapPin, Phone } from 'lucide-react';
import { ContactForm } from '@/components/ContactForm';

export const metadata: Metadata = { title: 'Contato' };

export default function ContactPage() {
  return <><section className="bg-light"><div className="container-wide py-16 sm:py-20"><span className="eyebrow">FALE COM A GENTE</span><h1 className="section-title mt-4">Estamos aqui para <span className="font-serif italic font-normal text-accent">cuidar do seu olhar.</span></h1><p className="mt-4 max-w-2xl text-sm leading-7 text-ink/65 sm:text-base">Tire suas dúvidas, conheça as opções ou venha experimentar seus favoritos na nossa loja em Varginha.</p></div></section><section className="container-wide grid gap-10 py-16 lg:grid-cols-[.75fr_1.25fr] lg:py-20"><div className="space-y-7"><div><h2 className="text-2xl font-semibold text-primary">Venha nos visitar</h2><p className="mt-2 text-sm leading-7 text-ink/60">Será um prazer receber você.</p></div><div className="space-y-5">{[
      { icon: MapPin, label: 'Endereço', value: 'Praça Quintino Bocaiuva, 61 · Loja 1\nCentro, Varginha/MG · 37002-180', href: 'https://www.google.com/maps/search/?api=1&query=Pra%C3%A7a+Quintino+Bocaiuva+61+Varginha+MG' },
      { icon: Phone, label: 'Telefone', value: '(35) 3221-6531', href: 'tel:+553532216531' },
      { icon: Instagram, label: 'Instagram', value: '@sulotica', href: 'https://www.instagram.com/sulotica/' },
    ].map(item => <a key={item.label} href={item.href} target={item.href.startsWith('http') ? '_blank' : undefined} rel={item.href.startsWith('http') ? 'noopener noreferrer' : undefined} className="flex gap-4 rounded-2xl border border-primary/10 p-5 transition hover:border-accent/40 hover:shadow-soft"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-accent/10 text-accent"><item.icon size={20} /></span><span><strong className="block text-xs uppercase tracking-[.13em] text-primary/55">{item.label}</strong><span className="mt-1 block whitespace-pre-line text-sm font-semibold leading-6 text-primary">{item.value}</span></span></a>)}<div className="flex gap-4 rounded-2xl border border-primary/10 p-5"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-accent/10 text-accent"><Clock size={20} /></span><span><strong className="block text-xs uppercase tracking-[.13em] text-primary/55">Horário</strong><span className="mt-1 block text-sm font-semibold text-primary">Confirme por telefone antes de visitar.</span></span></div></div></div><ContactForm /></section><section className="container-wide pb-20"><div className="overflow-hidden rounded-[1.75rem] bg-light"><iframe title="Mapa da Sul Ótica em Varginha" src="https://maps.google.com/maps?q=Pra%C3%A7a%20Quintino%20Bocaiuva%2061%2C%20Varginha%2C%20MG&t=&z=15&ie=UTF8&iwloc=&output=embed" loading="lazy" referrerPolicy="no-referrer-when-downgrade" className="h-[360px] w-full border-0" /></div></section></>;
}
