import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowRight, Eye, HeartHandshake, MapPin, Sparkles } from 'lucide-react';
import { Logo } from '@/components/Logo';

export const metadata: Metadata = { title: 'Nossa história' };

export default function AboutPage() {
  return <><section className="bg-primary text-white"><div className="container-wide grid items-center gap-10 py-16 lg:grid-cols-2 lg:py-24"><div><span className="eyebrow">NOSSA HISTÓRIA</span><h1 className="mt-5 text-[clamp(2.8rem,5vw,5rem)] font-semibold leading-[1.08] tracking-[-.05em]">Uma história feita <span className="font-serif italic font-normal text-accent">de novos olhares.</span></h1><p className="mt-6 max-w-xl text-sm leading-8 text-white/70 sm:text-base">A Sul Ótica nasceu em Varginha em 1980. Gerações depois, a mesma dedicação ao atendimento continua a inspirar cada novo capítulo.</p></div><div className="flex min-h-64 items-center justify-center rounded-[2rem] border border-white/15 bg-[#0e4277] p-10"><div className="scale-125"><Logo light /></div></div></div></section>
    <section className="container-wide grid gap-12 py-20 lg:grid-cols-[.85fr_1.15fr] lg:items-center lg:py-28"><div><span className="eyebrow">DESDE 1980</span><h2 className="section-title mt-4">Tradição que acompanha <span className="font-serif italic font-normal text-accent">o seu tempo.</span></h2><p className="mt-6 text-sm leading-8 text-ink/65 sm:text-base">Fundada por Geraldo Pressato, a Sul Ótica cresceu junto com Varginha. Rogério Pressato deu continuidade ao trabalho da família, e Robert Pressato representa a terceira geração à frente da loja.</p><p className="mt-4 text-sm leading-8 text-ink/65 sm:text-base">Em 2025, o espaço foi renovado para receber os clientes com ainda mais conforto. O cuidado pessoal e a atenção aos detalhes seguem no centro da experiência.</p><Link href="/contato" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-accent">Venha nos visitar <ArrowRight size={17} /></Link></div><div className="grid gap-4 sm:grid-cols-2"><div className="relative min-h-80 overflow-hidden rounded-[1.5rem] bg-light sm:translate-y-7"><Image src="/images/hero-editorial.png" alt="Imagem ilustrativa de campanha da Sul Ótica" fill sizes="(max-width: 640px) 100vw, 25vw" className="object-cover object-[66%_center]" /></div><div className="flex min-h-80 flex-col justify-end rounded-[1.5rem] bg-light p-8"><span className="text-[70px] font-black leading-none tracking-[-.08em] text-accent">46</span><p className="mt-3 text-sm font-semibold text-primary">anos de história em 2026</p><p className="mt-2 text-xs leading-6 text-ink/55">Um legado de cuidado com o olhar em Varginha.</p></div></div></section>
    <section className="bg-light py-20"><div className="container-wide"><div className="mb-9 max-w-xl"><span className="eyebrow">O QUE NOS MOVE</span><h2 className="section-title mt-3">Muito além de escolher óculos.</h2></div><div className="grid gap-5 md:grid-cols-3">{[
      { icon: Eye, title: 'Ver bem', text: 'Ajudar cada pessoa a encontrar uma solução que acompanhe seu dia a dia.' },
      { icon: HeartHandshake, title: 'Cuidar de perto', text: 'Ouvir, orientar e acolher em cada etapa da escolha.' },
      { icon: Sparkles, title: 'Olhar adiante', text: 'Unir a experiência construída desde 1980 a novas formas de descobrir seu estilo.' },
    ].map(item => <div key={item.title} className="rounded-[1.5rem] bg-white p-8"><item.icon size={28} className="text-accent" /><h3 className="mt-8 text-xl font-semibold text-primary">{item.title}</h3><p className="mt-3 text-sm leading-7 text-ink/60">{item.text}</p></div>)}</div></div></section>
    <section className="container-wide flex flex-col items-start justify-between gap-7 py-16 md:flex-row md:items-center"><div><span className="eyebrow"><MapPin size={15} /> NO CENTRO DE VARGINHA</span><h2 className="mt-3 text-3xl font-semibold tracking-tight text-primary">Conheça a Sul Ótica de perto.</h2><p className="mt-3 text-sm text-ink/60">R. Alves e Silva, 61 · Centro</p></div><Link href="/contato" className="btn-primary">Como chegar <ArrowRight size={17} /></Link></section>
  </>;
}
