import Link from 'next/link';
import Image from 'next/image';
import { ArrowUpRight, Glasses, ScanFace, Sun, Sparkles, MoveUpRight } from 'lucide-react';
import { HeroSection } from '@/components/HeroSection';
import { FeaturedCollection } from '@/components/FeaturedCollection';
import { Reveal } from '@/components/Reveal';
import { WhatsAppButton } from '@/components/WhatsAppButton';

export default function HomePage() {
  return <>
    <HeroSection />
    <section className="container-wide pb-12"><div className="category-paths">{[
      { icon: Glasses, n: '01', title: 'Para ver cada detalhe', label: 'ÓCULOS DE GRAU', href: '/catalogo?categoria=Grau' },
      { icon: Sun, n: '02', title: 'Para os seus dias de sol', label: 'ÓCULOS DE SOL', href: '/catalogo?categoria=Sol' },
      { icon: ScanFace, n: '03', title: 'Para descobrir você', label: 'VISAGISMO INTELIGENTE', href: '/visagismo' },
    ].map(item => <Link key={item.n} href={item.href}><item.icon size={29} strokeWidth={1.2} /><div><span>{item.label}</span><h2>{item.title}</h2></div><ArrowUpRight size={20} className="ml-auto" /></Link>)}</div></section>
    <div className="ticker" aria-label="Design, personalidade e novos pontos de vista"><div aria-hidden="true">{[0, 1, 2, 3].map(n => <span key={n}>DESIGN QUE EXPRESSA <Sparkles size={22} /> CONFORTO QUE FICA <Sparkles size={22} /> NOVOS PONTOS DE VISTA <Sparkles size={22} /></span>)}</div></div>
    <section id="colecao" className="container-wide section-space scroll-mt-36"><Reveal><FeaturedCollection /></Reveal></section>
    <section className="container-wide pb-20 lg:pb-28"><Reveal className="style-feature"><div className="style-art" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="face-outline"><svg viewBox="0 0 240 290" fill="none"><path d="M120 24C52 24 44 82 52 145C60 213 88 256 120 263C152 256 180 213 188 145C196 82 188 24 120 24Z" stroke="currentColor" strokeWidth="1" /><path d="M52 118H188M61 177H179M120 24V263M70 55L171 218M170 55L69 218M50 145L120 84L190 145L120 235Z" stroke="currentColor" strokeOpacity=".3" /><path d="M67 118C75 108 93 108 102 118M138 118C147 108 165 108 173 118M120 126L109 172H131M98 204Q120 219 142 204" stroke="currentColor" strokeWidth="2" /><rect x="57" y="99" width="50" height="40" rx="17" stroke="currentColor" strokeWidth="2" /><rect x="133" y="99" width="50" height="40" rx="17" stroke="currentColor" strokeWidth="2" /><path d="M107 114Q120 106 133 114" stroke="currentColor" strokeWidth="2" />{[[52,145],[188,145],[120,24],[120,263],[61,177],[179,177]].map(([cx,cy]) => <circle key={cx + '-' + cy} cx={cx} cy={cy} r="3" fill="currentColor" />)}</svg><div className="scan-line" /></div><span className="scan-label"><span className="status-dot" /> UM OLHAR SÓ SEU</span></div><div className="style-copy"><span className="eyebrow">TECNOLOGIA ENCONTRA PERSONALIDADE</span><h2>Combina com<br />seu rosto.<br /><em>E com você.</em></h2><p>Seus traços são únicos. Com uma foto, nosso visagismo ajuda você a descobrir formatos de armação e explorar novas versões do seu estilo.</p><Link href="/visagismo" className="btn-highlight">Descobrir meu estilo <ArrowUpRight size={18} /></Link><span className="mt-5 block text-xs text-white/50">Uma sugestão de estilo. A escolha é sempre sua.</span></div></Reveal></section>
    <section className="container-wide pb-20 lg:pb-28"><Reveal className="about-teaser"><div className="about-image"><Image src="/images/frame-champagne.png" alt="Detalhes de uma armação transparente champagne" fill sizes="(max-width: 768px) 100vw, 45vw" className="object-cover" /><span>MENOS PADRÕES.<br />MAIS PERSONALIDADE.</span></div><div><span className="eyebrow">PRAZER, FÁBIO ÓTICA.</span><h2 className="section-title mt-5">A vida tem muitos<br />ângulos. <em>Encontre o seu.</em></h2><p className="mt-6 max-w-md text-sm leading-8 text-ink/65">Acreditamos que óculos são mais do que um acessório. São a forma como você vê o mundo — e como escolhe se apresentar a ele.</p><p className="mt-4 max-w-md text-sm leading-8 text-ink/65">Por isso, reunimos design, conforto e uma escuta atenta para ajudar você a encontrar uma escolha que faça sentido de verdade.</p><Link href="/sobre" className="text-link mt-8">Conheça a Fábio Ótica <ArrowUpRight size={18} /></Link></div></Reveal></section>
    <section className="contact-strip"><div className="container-wide flex flex-col justify-between gap-8 py-14 md:flex-row md:items-center"><div><span className="eyebrow">SEU NOVO OLHAR COMEÇA EM UMA CONVERSA</span><h2 className="mt-3 text-3xl tracking-[-.04em] sm:text-4xl">Vamos encontrar <em className="font-serif">o seu?</em> <MoveUpRight className="ml-2 inline" strokeWidth={1} /></h2></div><WhatsAppButton>Fale com a gente</WhatsAppButton></div></section>
  </>;
}
