import Link from 'next/link';
import { ArrowRight, BadgeCheck, Camera, HeartHandshake, MapPin, ScanFace, Sparkles } from 'lucide-react';
import { HeroSection } from '@/components/HeroSection';
import { ProductCard } from '@/components/ProductCard';
import { WhatsAppButton } from '@/components/WhatsAppButton';
import { products } from '@/lib/mock-data';

export default function HomePage() {
  return <>
    <HeroSection />
    <section className="border-b border-primary/5 bg-white"><div className="container-wide grid gap-5 py-7 md:grid-cols-3 md:gap-8"><div className="flex items-center gap-4"><BadgeCheck className="shrink-0 text-accent" size={25} /><span><strong className="block text-sm text-primary">Tradição desde 2000</strong><small className="text-xs text-ink/55">Décadas dedicadas à sua visão</small></span></div><div className="flex items-center gap-4"><HeartHandshake className="shrink-0 text-accent" size={25} /><span><strong className="block text-sm text-primary">Atendimento próximo</strong><small className="text-xs text-ink/55">Pessoas cuidando de pessoas</small></span></div><div className="flex items-center gap-4"><MapPin className="shrink-0 text-accent" size={25} /><span><strong className="block text-sm text-primary">No coração de Sua Cidade</strong><small className="text-xs text-ink/55">Venha experimentar na loja</small></span></div></div></section>
    <section className="container-wide py-20 lg:py-28"><div className="mb-11 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><span className="eyebrow">ESCOLHAS QUE INSPIRAM</span><h2 className="section-title mt-3">Encontre a armação <br /><span className="font-serif italic font-normal text-accent">que é a sua cara.</span></h2></div><Link href="/catalogo" className="inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-accent">Ver todo o catálogo <ArrowRight size={17} /></Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{products.slice(0, 4).map(product => <ProductCard key={product.id} product={product} />)}</div><p className="mt-5 text-center text-xs text-ink/40">Coleção, imagens e preços ilustrativos para apresentação do protótipo.</p></section>
    <section className="bg-light py-20 lg:py-28"><div className="container-wide"><div className="mx-auto max-w-2xl text-center"><span className="eyebrow">TECNOLOGIA COM PROPÓSITO</span><h2 className="section-title mt-4">Seu estilo, visto <span className="font-serif italic font-normal text-accent">por outro ângulo.</span></h2><p className="mt-5 text-sm leading-7 text-ink/65 sm:text-base">O visagismo facial sugere formatos de armação a partir de uma foto. Uma experiência simples para começar sua escolha com mais confiança.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[
      { n: '01', icon: Camera, title: 'Envie sua foto', text: 'Escolha uma foto frontal com boa luz ou use a câmera do dispositivo.' },
      { n: '02', icon: ScanFace, title: 'Descubra seus traços', text: 'A ferramenta observa o contorno do rosto e prepara sugestões de estilo.' },
      { n: '03', icon: Sparkles, title: 'Experimente opções', text: 'Veja armações recomendadas e converse com nossa equipe.' },
    ].map(step => <div key={step.n} className="relative rounded-[1.5rem] bg-white p-8 shadow-[0_8px_25px_rgba(10,55,102,.035)]"><span className="absolute right-7 top-6 text-4xl font-black text-primary/5">{step.n}</span><span className="flex h-13 w-13 items-center justify-center rounded-2xl bg-accent/10 p-3 text-accent"><step.icon size={25} /></span><h3 className="mt-8 text-xl font-semibold text-primary">{step.title}</h3><p className="mt-3 text-sm leading-7 text-ink/60">{step.text}</p></div>)}</div><div className="mt-10 text-center"><Link href="/visagismo" className="btn-primary"><ScanFace size={18} />Experimentar visagismo<ArrowRight size={17} /></Link></div></div></section>
    <section className="container-wide py-20 lg:py-28"><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><div className="relative overflow-hidden rounded-[2rem] bg-primary p-10 text-white sm:p-14"><span className="text-[100px] font-black leading-none tracking-[-.09em] text-accent sm:text-[140px]">2000</span><span className="mt-2 block text-sm font-semibold uppercase tracking-[.25em] text-white/60">O início de uma história</span><div className="absolute -bottom-20 -right-20 h-72 w-72 rounded-full border-[45px] border-accent/10" /></div><div><span className="eyebrow">A ESSÊNCIA DA SUL ÓTICA</span><h2 className="section-title mt-4">Olhar para o futuro, <span className="font-serif italic font-normal text-accent">sem esquecer de onde viemos.</span></h2><p className="mt-5 text-sm leading-8 text-ink/65 sm:text-base">Desde 2000, a Ótica Fábio faz parte da história de Sua Cidade. O cuidado próximo que construiu essa trajetória agora encontra novas ferramentas para ajudar cada pessoa a se reconhecer no espelho.</p><Link href="/sobre" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-accent">Conheça nossa história <ArrowRight size={18} /></Link></div></div></section>
    <section className="bg-primary py-16 text-white"><div className="container-wide flex flex-col items-start justify-between gap-7 md:flex-row md:items-center"><div><span className="text-xs font-bold uppercase tracking-[.2em] text-accent">ESTAMOS PERTO DE VOCÊ</span><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Vamos encontrar seus próximos óculos?</h2><p className="mt-3 text-sm text-white/65">Conheça as opções e tire suas dúvidas com nossa equipe.</p></div><WhatsAppButton className="shrink-0">Conversar com a Ótica Fábio</WhatsAppButton></div></section>
  </>;
}
